In [79]:
import pandas as pd
import numpy as np
from sklearn import preprocessing

# 1. Масштабирование:
# а. Нормализовать признак - median_income
# б. Привести признак - population к масштабу от 0 до 100

HOUSING_PATH = "Материалы_к_лекции_1/data/housing.csv"
housing = pd.read_csv(HOUSING_PATH)
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [82]:
#а. Нормализовать признак - median_income
min_max_scaler = preprocessing.MinMaxScaler()
housing_column_to_normalize = housing[["median_income"]]
housing_column_to_normalize.head()
housing_column_normalized = min_max_scaler.fit_transform(housing_column_to_normalize)
housing_column_normalized

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [83]:
# б. Привести признак - population к масштабу от 0 до 100

min_max_scaler = preprocessing.MinMaxScaler(feature_range = (0,100))
housing_column_to_normalize = housing[["population"]]
housing_column_to_normalize.head()
housing_column_normalized = min_max_scaler.fit_transform(housing_column_to_normalize)
housing_column_normalized

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [91]:
# 2. Заполнение пропусков:
# а. Заполнить пропуски в столбце total_bedrooms средними значениями по категориям столбца ocean_proximity
# Например, если пропущенно значение в строке с категорией INLAND, нужно заполнить его средним значением по этой категории


housing['total_bedrooms']= housing.groupby("ocean_proximity").transform(lambda x: x.fillna(x.mean()))

housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,-122.23,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,-122.22,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,-122.24,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,-122.25,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,-122.25,565.0,259.0,3.8462,342200.0,NEAR BAY

In [100]:
# 3. Категорийные атрибуты:
# а. Посчитать среднее кол-во комнат в строке (total_rooms/households)
# б. Разбить полученный столбец на группы на ваше усмотрение (Например, 1 комната, 2 комнаты, 3 и более комнат)

housing['average_room_num'] = (housing.total_rooms/ housing.households).apply(round)
housing.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,average_room_num
0,-122.23,37.88,41.0,880.0,-122.23,322.0,126.0,8.3252,452600.0,NEAR BAY,7
1,-122.22,37.86,21.0,7099.0,-122.22,2401.0,1138.0,8.3014,358500.0,NEAR BAY,6
2,-122.24,37.85,52.0,1467.0,-122.24,496.0,177.0,7.2574,352100.0,NEAR BAY,8
3,-122.25,37.85,52.0,1274.0,-122.25,558.0,219.0,5.6431,341300.0,NEAR BAY,6
4,-122.25,37.85,52.0,1627.0,-122.25,565.0,259.0,3.8462,342200.0,NEAR BAY,6

In [109]:
# б. Разбить полученный столбец на группы на ваше усмотрение (Например, 1 комната, 2 комнаты, 3 и более комнат)

housing['rooms_in_house'] = pd.cut(housing['average_room_num'], bins=[0,1,2,99], labels=['1 команата', '2 комнаты','3 и более комнат'])

housing.sort_values("average_room_num")

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity,average_room_num,rooms_in_house
5916,-118.44,34.28,46.0,11.0,-118.44,24.0,13.0,2.8750,162500.0,<1H OCEAN,1,1 команата
4552,-118.24,34.04,52.0,116.0,-118.24,171.0,92.0,1.0769,112500.0,<1H OCEAN,1,1 команата
8219,-118.21,33.79,33.0,32.0,-118.21,96.0,36.0,4.5938,112500.0,NEAR OCEAN,1,1 команата
4550,-118.23,34.05,52.0,346.0,-118.23,346.0,251.0,2.5313,225000.0,<1H OCEAN,1,1 команата
14818,-117.11,32.68,36.0,26.0,-117.11,58.0,23.0,1.9107,125000.0,NEAR OCEAN,1,1 команата
4602,-118.27,34.05,12.0,535.0,-118.27,1194.0,365.0,1.2012,275000.0,<1H OCEAN,1,1 команата
4587,-118.27,34.05,37.0,350.0,-118.27,1122.0,248.0,2.7634,137500.0,<1H OCEAN,1,1 команата
17820,-121.90,37.37,20.0,78.0,-121.90,120.0,69.0,1.0938,187500.0,<1H OCEAN,1,1 команата
3126,-117.79,35.21,4.0,2.0,-117.79,6.0,2.0,2.3750,137500.0,INLAND,1,1 команата
4877,-118.25,34.02,50.0,180.0,-118.25,356.0,76.0,2.1944,158300.0,<1H OCEAN,2,2 комнаты
4634,-118.30,34.07,28.0,5221.0,-118.30,5840.0,2374.0,1.8829,300000.0,<1H OCEAN,2,2 комнаты
15790,-122.40,37.77,52.0,144.0,-122.40,1061.0,68.0,4.3958,225000.0,NEAR BAY,2,2 комнаты
4632,-118.31,34.06,34.0,2470.0,-118.31,2326.0,1055.0,1.9038,325000.0,<1H OCEAN,2,2 комнаты
4635,-118.30,34.06,43.0,1366.0,-118.30,942.0,672.0,1.6953,150000.0,<1H OCEAN,2,2 комнаты
4631,-118.30,34.06,20.0,1782.0,-118.30,1749.0,823.0,2.2094,75000.0,<1H OCEAN,2,2 комнаты
4636,-118.29,34.06,42.0,3894.0,-118.29,6846.0,2156.0,1.5553,70000.0,<1H OCEAN,2,2 комнаты
4813,-118.28,34.05,35.0,1627.0,-118.28,3013.0,791.0,1.5565,152500.0,<1H OCEAN,2,2 комнаты
4638,-118.29,34.06,46.0,1759.0,-118.29,2716.0,877.0,2.1637,350000.0,<1H OCEAN,2,2 комнаты
4637,-118.29,34.06,27.0,2456.0,-118.29,4137.0,1104.0,1.5954,187500.0,<1H OCEAN,2,2 комнаты
17063,-122.23,37.49,11.0,840.0,-122.23,1338.0,345.0,2.3333,241700.0,NEAR OCEAN,2,2 комнаты
7424,-118.21,33.96,48.0,284.0,-118.21,422.0,119.0,1.2826,145500.0,<1H OCEAN,2,2 комнаты
4639,-118.30,34.06,47.0,1390.0,-118.30,2860.0,827.0,1.4680,137500.0,<1H OCEAN,2,2 комнаты
4641,-118.30,34.06,33.0,2437.0,-118.30,3906.0,1084.0,2.0332,270000.0,<1H OCEAN,2,2 комнаты
15793,-122.42,37.76,37.0,1291.0,-122.42,1846.0,557.0,1.3365,225000.0,NEAR BAY,2,2 комнаты
20352,-119.09,34.22,8.0,40.0,-119.09,309.0,16.0,4.0208,52500.0,NEAR OCEAN,2,2 комнаты
4643,-118.30,34.06,23.0,2512.0,-118.30,3720.0,1118.0,1.7896,322200.0,<1H OCEAN,2,2 комнаты
2004,-119.79,36.74,52.0,173.0,-119.79,401.0,84.0,2.1094,75000.0,INLAND,2,2 комнаты
7483,-118.22,33.93,30.0,443.0,-118.22,903.0,189.0,2.1964,125000.0,<1H OCEAN,2,2 комнаты
15778,-122.41,37.78,52.0,1534.0,-122.41,1520.0,614.0,1.4554,375000.0,NEAR BAY,2,2 комнаты
4614,-118.29,34.08,43.0,3056.0,-118.29,3920.0,1304.0,1.9250,300000.0,<1H OCEAN,2,2 комнаты
...,...,...,...,...,...,...,...,...,...,...,...,...
2397,-119.32,37.06,15.0,3111.0,-119.32,276.0,107.0,5.1314,179200.0,INLAND,29,3 и более комнат
11849,-121.00,39.75,8.0,1116.0,-121.00,27.0,39.0,2.5893,83000.0,INLAND,29,3 и более комнат
1234,-120.33,38.26,13.0,2962.0,-120.33,252.0,103.0,4.4063,155800.0,INLAND,29,3 и более комнат
18681,-121.82,36.86,17.0,1573.0,-121.82,142.0,55.0,2.1719,420000.0,NEAR OCEAN,29,3 и более комнат
13964,-116.86,34.24,19.0,5411.0,-116.86,441.0,185.0,3.1324,132000.0,INLAND,29,3 и более комнат
1024,-120.00,38.52,16.0,3045.0,-120.00,202.0,102.0,3.1500,140600.0,INLAND,30,3 и более комнат
3086,-118.59,35.72,28.0,1491.0,-118.59,98.0,48.0,1.4205,90000.0,INLAND,31,3 и более комнат
1102,-121.54,40.06,17.0,858.0,-121.54,47.0,27.0,2.4028,67500.0,INLAND,32,3 и более комнат
1239,-120.27,38.31,13.0,3297.0,-120.27,267.0,97.0,3.0750,108300.0,INLAND,34,3 и более комнат
1978,-120.32,38.71,13.0,1115.0,-120.32,86.0,32.0,3.5667,115600.0,INLAND,35,3 и более комнат
9683,-118.99,37.63,10.0,7744.0,-118.99,483.0,224.0,3.2917,231800.0,INLAND,35,3 и более комнат
13965,-116.86,34.23,13.0,4760.0,-116.86,309.0,132.0,5.4618,147800.0,INLAND,36,3 и более комнат
10080,-120.24,39.35,8.0,4195.0,-120.24,291.0,115.0,3.4792,180800.0,INLAND,36,3 и более комнат
11716,-120.10,39.19,18.0,3824.0,-120.10,241.0,106.0,5.5456,360000.0,INLAND,36,3 и более комнат
20094,-120.03,38.19,26.0,7005.0,-120.03,416.0,189.0,2.1250,132500.0,INLAND,37,3 и более комнат
13950,-117.07,34.24,21.0,4773.0,-117.07,337.0,130.0,3.9375,115000.0,INLAND,37,3 и более комнат
1926,-120.30,38.90,11.0,1961.0,-120.30,113.0,53.0,0.9227,95500.0,INLAND,37,3 и более комнат
1872,-119.93,38.94,27.0,1709.0,-119.93,97.0,44.0,2.4917,200000.0,INLAND,39,3 и более комнат
11833,-120.18,39.28,14.0,10098.0,-120.18,701.0,254.0,4.0819,141300.0,INLAND,40,3 и более комнат
11832,-120.33,39.30,16.0,868.0,-120.33,44.0,21.0,3.0000,175000.0,INLAND,41,3 и более комнат
1240,-120.19,38.42,11.0,1568.0,-120.19,82.0,33.0,3.1250,77500.0,INLAND,48,3 и более комнат
2395,-119.34,37.12,23.0,1881.0,-119.34,64.0,37.0,3.8750,125000.0,INLAND,51,3 и более комнат
9676,-119.02,37.64,14.0,5919.0,-119.02,265.0,112.0,3.2431,221400.0,INLAND,53,3 и более комнат
11707,-120.06,39.15,22.0,2213.0,-120.06,98.0,42.0,1.1912,170000.0,INLAND,53,3 и более комнат
1912,-120.16,39.01,16.0,1463.0,-120.16,54.0,26.0,4.9750,206300.0,INLAND,56,3 и более комнат
11862,-121.25,40.27,25.0,958.0,-121.25,28.0,16.0,2.6250,67500.0,INLAND,60,3 и более комнат
12447,-114.49,33.97,17.0,2809.0,-114.49,83.0,45.0,1.6154,87500.0,INLAND,62,3 и более комнат
1913,-120.06,39.01,19.0,2967.0,-120.06,112.0,48.0,4.0714,437500.0,INLAND,62,3 и более комнат
1979,-120.08,38.80,34.0,1988.0,-120.08,36.0,15.0,4.6250,162500.0,INLAND,133,NaN
1914,-120.10,38.91,33.0,1561.0,-120.10,30.0,11.0,1.8750,500001.0,INLAND,142,NaN